name: Run Pytest
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - run: uv sync --all-extras --all-groups
      - run: uv run pytest
      - run: ruff check --exit-non-zero-on-fix --verbose
      - run: ruff format --check --verbose
